### ISSUE TITLE
[META]: TO DO LIST APP

### ISSUE THREAD

**Issue by DanielBrando96** [DanielBrando96/TodoBootcamp#2]
## Summary
Te objective of this repository is to create a To Do list App capable of adding new tasks, checking them as completed, re organize tasks order and changing from light to dark mode. In order to acomplish this, I've created a series of taks to complete that would yield a MVP. These are the following:

## Steps to Complete

- [ ] Create Package Base Structure #1 
- [ ] Configure styling
- [ ] Create task actions
- [ ] Make a dark mode button
